### ISSUE TITLE
Add Account

### ISSUE THREAD

**Issue by turpez** [s3840619/OverwatchAccountViewer#1]
Hello, I can't add an account, how do I do ?

**Comment by turpez** [comment]
![image](https://github.com/dab-bot/OverwatchAccountViewer/assets/29740508/0eee481f-f11c-4167-bbca-40f6485548d0)

**Comment by aaronfisher-code** [comment]
Hi @turpez, unfortunately this repository is no longer supported, It was built back in overwatch 1 days to handle those accounts and all the APIs it had dependencies for are now deprecated. I'm moving this repo to archived to reflect this change
